// <auto-generated />
namespace MVVM_DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class recipeingredient_unitnotrequired : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(recipeingredient_unitnotrequired));
        
        string IMigrationMetadata.Id
        {
            get { return "202101041909033_recipeingredient_unitnotrequired"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
